name: Pipeline para Deploy da aplicação Java

on:
   push:
     branches:
        - main
   pull_request:
     branches:
        - main

jobs:
    build:
       name: Compilação do projeto
       runs-on: ubuntu-22.04
       steps:
          - name: Checkout do código
            uses: actions/checkout@v2

          - name: Configuração do JDK 21
            uses: actions/setup-java@v2
            with:
                java-version: "21"
                distribution: "temurin"

          - name: Compilar o projeto com o Maven
            run: mvn clean package -DskipTests

          - name: Pegar os arquivos da pasta target
            run: ls -la target

          - name: Gerando o arquivo JAR compilado do projeto
            uses: actions/upload-artifact@v4
            with:
                name: jar-file
                path: target/*.jar